# Generated by Django 2.2.13 on 2020-07-13 20:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Limits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('restaurants', models.PositiveIntegerField(blank=True, null=True)),
                ('branches', models.PositiveIntegerField(blank=True, null=True)),
                ('menus', models.PositiveIntegerField(blank=True, null=True)),
                ('products', models.PositiveIntegerField(blank=True, null=True)),
                ('order_instead', models.BooleanField(blank=True, null=True)),
                ('order_take_away', models.BooleanField(blank=True, null=True)),
                ('order_delivery', models.BooleanField(blank=True, null=True)),
                ('payment_gateway', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(default=1, help_text='Months')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('limits', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Limits')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration', models.DateField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Plan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
