# Generated by Django 2.2.13 on 2020-07-13 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Limits',
            new_name='Licensing',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='limits',
            new_name='licensing',
        ),
    ]
