# Generated by Django 2.2.13 on 2020-07-13 00:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.PositiveIntegerField()),
                ('instead', models.BooleanField(default=True)),
                ('take_away', models.BooleanField(default=True)),
                ('delivery', models.BooleanField(default=True)),
                ('use_restaurant_credentials', models.BooleanField(default=True, verbose_name='Use Restaurant Mercadopago Credentials')),
                ('mp_branch_public_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='Publick Key (Mercadopago)')),
                ('mp_branch_access_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='Access Token (Mercadopago)')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menus/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=100)),
                ('cuit', models.PositiveIntegerField()),
                ('website', models.URLField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/')),
                ('slug', models.SlugField()),
                ('mp_public_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='Publick Key (Mercadopago)')),
                ('mp_access_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='Access Token (Mercadopago)')),
            ],
        ),
        migrations.CreateModel(
            name='MenuLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_product_price', models.BooleanField(default=True)),
                ('custom_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.Menu')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.Product')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.Restaurant'),
        ),
    ]
