# Generated by Django 2.2.13 on 2020-07-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0003_auto_20200713_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='use_restaurant_credentials',
            field=models.BooleanField(default=True, verbose_name='Use Mercadopago Keys from Restaurant'),
        ),
    ]
