# Generated by Django 2.2.13 on 2020-07-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20200712_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preference_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
