# Generated by Django 2.2.13 on 2020-07-13 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_auto_20200713_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('instead', 'instead'), ('take_away', 'take away'), ('delivery', 'delivery')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 15, 1, 58, 238403)),
        ),
    ]
