# Generated by Django 2.2.13 on 2020-07-13 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_auto_20200713_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 15, 2, 38, 960840)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('instead', 'instead'), ('take_away', 'take away'), ('delivery', 'delivery')], default='instead', max_length=10),
        ),
    ]
